description = """
    Fix the wheel group GID.

    In Solus historically sudo was used as the admin group, and wheel was let unused.
    We wish to switch admin users to be in the wheel group instead to reduce maintenance burden,
    but, the wheel group had a bogus id of > 1000 specified by the baselayout package.
"""

[[group-update]]
name = "wheel"
id = 30
